import type { CelestialEvent } from '@/types';

export const celestialEvents: CelestialEvent[] = [
    {
        name: "Great Conjunction",
        description: "Rare alignment of Rutilus, Spectris, Viridis, and Aetheris in a 'Celestial Crescent,' a prophetic night event.",
        type: 'conjunction',
        primaryBodies: ["Rutilis", "Spectris", "Viridis", "Aetheris"],
        longitudeTolerance: 0.1,
        minSeparation: 6,
        sunSeparationMultiplier: 10, // Allow closer approach to suns
        viewingLongitude: 180,
        visibilityCondition: 'night',
    },
    {
        name: "Celestial Origin Alignment",
        description: "The rare alignment of the five inner planets, recreating their positions at the dawn of the Sebakan calendar (Year 0, Day 1).",
        type: 'conjunction',
        primaryBodies: ["Rutilis", "Sebaka", "Spectris", "Viridis", "Aetheris"],
        longitudeTolerance: 1.0,
        minSeparation: 0.5,
        sunSeparationMultiplier: 1.0,
        viewingLongitude: 180,
        visibilityCondition: 'night',
    },
    {
        name: "Gathering of Witnesses",
        description: "Annual visibility of Rutilus, Spectris, Viridis, Aetheris, and Beacon in a loose arc, a festive night event.",
        type: 'cluster',
        primaryBodies: ["Rutilis", "Spectris", "Viridis", "Aetheris"],
        secondaryBodies: ["Beacon"],
        longitudeTolerance: 30,
        viewingLongitude: 270,
        visibilityCondition: 'night',
    },
    {
        name: "Twin Conjunction",
        description: "Rutilus and Spectris appear close, creating a 'Double Ember' effect, a twilight event.",
        type: 'conjunction',
        primaryBodies: ["Rutilis", "Spectris"],
        longitudeTolerance: 30,
        viewingLongitude: 240,
        visibilityCondition: 'twilight',
    },
    {
        name: "Triad Alignment",
        description: "Rutilus, Spectris, and Viridis form a triangle, the 'Triad Lantern' during the Lantern Festival, at night.",
        type: 'triangle',
        primaryBodies: ["Rutilis", "Spectris", "Viridis"],
        longitudeTolerance: 1,
        viewingLongitude: 210,
        visibilityCondition: 'night',
    },
    {
        name: "Quadrant Convergence",
        description: "Rutilus, Spectris, Viridis, and Aetheris align with Beacon, the 'Quadrant Veil' for Veil Nights.",
        type: 'conjunction',
        primaryBodies: ["Rutilis", "Spectris", "Viridis", "Aetheris"],
        secondaryBodies: ["Beacon"],
        longitudeTolerance: 30,
        viewingLongitude: 270,
        visibilityCondition: 'night',
    },
    {
        name: "Aetheris Dominance",
        description: "Aetheris at periapsis forms a 'Blue Halo,' a night event for Halo Ascendance.",
        type: 'dominance',
        primaryBodies: ["Aetheris"],
        secondaryBodies: ["Spectris", "Viridis"],
        longitudeTolerance: 180, // Not relevant for dominance
        minSeparation: 20,
        viewingLongitude: 180,
        visibilityCondition: 'night',
    },
    {
        name: "Pre-Conjunction Prelude",
        description: "Near-alignment of inner planets, the 'Pre-Conjunction Blaze,' a twilight event before Great Conjunction.",
        type: 'cluster',
        primaryBodies: ["Rutilis", "Spectris", "Viridis", "Aetheris"],
        longitudeTolerance: 20,
        sunSeparationMultiplier: 0.9,
        viewingLongitude: 90,
        visibilityCondition: 'twilight',
    },
    {
        name: "Spectris-Viridis Occultation",
        description: "Rare eclipse, a 'Ringed Eclipse,' at night.",
        type: 'occultation',
        primaryBodies: ["Spectris", "Viridis"],
        longitudeTolerance: 0.1,
        overlapThreshold: 0.9,
        viewingLongitude: 170,
        visibilityCondition: 'night',
    },
    {
        name: "Spectris-Aetheris Occultation",
        description: "Rare 'Giant’s Veil' eclipse, at night.",
        type: 'occultation',
        primaryBodies: ["Spectris", "Aetheris"],
        longitudeTolerance: 0.1,
        overlapThreshold: 0.9,
        viewingLongitude: 185,
        visibilityCondition: 'night',
    },
    {
        name: "Viridis-Aetheris Occultation",
        description: "Rare 'Storm Shroud' eclipse, at night.",
        type: 'occultation',
        primaryBodies: ["Viridis", "Aetheris"],
        longitudeTolerance: 0.3,
        overlapThreshold: 0.5,
        viewingLongitude: 190,
        visibilityCondition: 'night',
    },
    {
        name: "The Great Eclipse",
        description: "Extremely rare occultation of all three, a 'Triple Cascade.'",
        type: 'occultation',
        primaryBodies: ["Viridis", "Spectris", "Aetheris"],
        longitudeTolerance: 0.1,
        overlapThreshold: 0.9,
        sunSeparationMultiplier: 0.5, // Very close approach allowed
        viewingLongitude: 188,
        visibilityCondition: 'night',
    },
];
