
import type { PlanetData, StarData } from "@/types";

const AU_TO_UNITS = 150;

export const initialStars: StarData[] = [
  {
      name: "Alpha", color: "#FFD700", size: 6.96, orbitPeriodDays: 26,
      type: 'Star', classification: 'G-type Yellow Dwarf',
      orbitalRole: 'Central Binary (orbits common barycenter)', orbitalPeriod: '26 Earth days (0.08 Sebakan years)', orbitalDistance: '0.2 AU',
      radius: '~1.0 R☉', mass: '1.0', luminosity: 1,
      surface: 'Typical yellow dwarf stellar surface, radiating warm golden light.',
      characteristics: 'Dominant light source, slightly larger and more luminous than Twilight.',
      appearance: 'Appears as the primary sun, a bright golden disk. Creates vibrant golden sunrises, primary driver of day-night cycle.',
      lore: 'Symbolizes action and passion in Hypodia’s Sky-Writing, revered as a life-giving force.'
  },
  {
      name: "Twilight", color: "#D95B00", size: 4.87, orbitPeriodDays: 26,
      type: 'Star', classification: 'K-type Orange Dwarf',
      orbitalRole: 'Central Binary (orbits common barycenter)', orbitalPeriod: '26 Earth days (0.08 Sebakan years)', orbitalDistance: '0.2 AU',
      radius: '~0.7 R☉', mass: '0.6', luminosity: 0.7,
      surface: 'Typical orange dwarf stellar surface, emitting a warm reddish glow.',
      characteristics: 'Less luminous than Alpha, creates a subtler light.',
      appearance: 'Appears as a secondary sun, smaller and redder than Alpha. Visible during day, prominent at dusk, creating reddish sunsets.',
      lore: 'Represents quiet strength and endurance in Hypodia’s Sky-Writing, a counterpoint to Alpha’s vibrancy.'
  },
  {
      name: "Beacon", color: "#B4DCFF", size: 27.84, orbitPeriodDays: 724464, orbitRadius: 200 * AU_TO_UNITS, initialPhase: 0,
      type: 'Star', classification: 'B-type Blue-White Giant',
      orbitalRole: 'Distant Companion (orbits common barycenter of Alpha-Twilight)', orbitalPeriod: '~2,236 Sebakan years (724,464 days)', orbitalDistance: '200 AU',
      radius: '~4 R☉', mass: '5.0', luminosity: 1000,
      surface: 'Brilliant blue-white giant, intensely luminous.',
      characteristics: 'Significantly more luminous than Alpha and Twilight combined. Hosts its own planetary subsystem (Gelidis, Liminis).',
      appearance: 'A brilliant, unblinking point of light (brighter than Sirius), often visible at twilight and occasionally during the day. Its slow generational shift provides a marker for cultural ages.',
      lore: 'Marks long-term "Great Years." Symbolizes constancy and divine oversight in Hypodia’s Sky-Writing, a guiding star for navigation and major rituals.'
  },
];

export const initialPlanets: PlanetData[] = [
  {
      name: "Rutilis", color: "#FF6600", size: 3.189, orbitRadius: 0.7 * AU_TO_UNITS, orbitPeriodDays: 169, eccentric: true, eccentricity: 0.1, initialPhase: 0,
      type: 'Planet', classification: 'Terrestrial',
      orbitalRole: 'Innermost planet orbiting Alpha-Twilight binary', orbitalPeriod: '0.522 Sebakan years (169 days)', orbitalDistance: '0.7 AU (periapsis 0.63 AU, apoapsis 0.77 AU)',
      rotation: '40 days', axialTilt: '10°', moons: 'None',
      radius: '0.5 R⊕', mass: '~0.3 M⊕',
      surface: 'Scorched, sulfur-yellow crust with bleeding magma lines, thin atmosphere with volcanic outgassing.',
      characteristics: 'Intense heat due to proximity to binary. Eccentricity (e=0.1).',
      appearance: 'Bright, ember-like point of light. Visible at twilight, occasionally during day. Synodic Period: ~1.091 Sebakan Years.',
      lore: 'Seen as a fiery, untamed world in Hypodia’s Sky-Writing, symbolizing raw passion.',
      rotationPeriodHours: 960,
  },
  {
      name: "Sebaka", color: "#0096C8", size: 6.371, orbitRadius: 1.08 * AU_TO_UNITS, orbitPeriodDays: 324, eccentric: true, eccentricity: 0.05, initialPhase: 0,
      type: 'Planet', classification: 'Terrestrial (Homeworld)',
      orbitalRole: 'Second planet orbiting Alpha-Twilight binary', orbitalPeriod: '1 Sebakan year (324 days)', orbitalDistance: '1.08 AU (periapsis 1.026 AU, apoapsis 1.134 AU)',
      rotation: '24 hours', axialTilt: '23.5°', moons: 'None',
      radius: '1 R⊕', mass: '1 M⊕',
      surface: 'Earth-like, with oceans, continents, and a breathable atmosphere.',
      characteristics: 'Habitable zone, supports life. Eccentricity (e=0.05).',
      appearance: 'N/A (observer’s planet). Hosts vibrant sunrises/sunsets from Alpha and Twilight.',
      lore: 'Defines year (324 days, 12 months of 27 days). Central to Hypodia’s Sky-Writing.',
      rotationPeriodHours: 24,
  },
  {
      name: "Spectris", color: "#B4B4C8", size: 5.097, orbitRadius: 2.0 * AU_TO_UNITS, orbitPeriodDays: 818, eccentric: true, eccentricity: 0.2, initialPhase: 0,
      type: 'Planet', classification: 'Terrestrial',
      orbitalRole: 'Third planet orbiting Alpha-Twilight binary', orbitalPeriod: '2.525 Sebakan years (818 days)', orbitalDistance: '2.0 AU (periapsis 1.6 AU, apoapsis 2.4 AU)',
      rotation: '30 hours', axialTilt: '15°', moons: '1 (28-day orbital period)',
      radius: '0.8 R⊕', mass: '~0.7 M⊕',
      surface: 'Hazy, greyish-white atmosphere, iridescent icy rings.',
      characteristics: 'High eccentricity (e = 0.2) causes significant brightness variations.',
      appearance: 'Fist-sized orb with shimmering rings. Prominent at sunset, visible at night. Synodic Period: ~1.660 Sebakan Years.',
      lore: 'Called the Calendar Planet, its subtle shifts inspire myths of revelation. Marks months via its sunset position and 28-day moon phases.',
      rotationPeriodHours: 30,
  },
  {
    name: "Viridis",
    color: "#9ACD32",
    size: 8.282, // 1.3 R⊕
    orbitRadius: 3.0 * AU_TO_UNITS,
    orbitPeriodDays: 1500,
    eccentric: true,
    eccentricity: 0.1,
    initialPhase: 0,
    type: 'Planet',
    classification: 'Terrestrial',
    orbitalRole: 'Fourth planet orbiting Alpha-Twilight binary',
    orbitalPeriod: '4.630 Sebakan years (1,500 days)',
    orbitalDistance: '3.0 AU (periapsis 2.7 AU, apoapsis 3.3 AU)',
    rotation: '20 hours',
    axialTilt: '20°',
    moons: 'None',
    radius: '1.3 R⊕',
    mass: '2.0 M⊕',
    surface: 'Sulfur-yellow crust, bleeding magma lines, thick atmosphere with volcanic plumes.',
    characteristics: 'Intense 27-day volcanic cycle (albedo 0.1–0.5). Eccentricity (e=0.1).',
    appearance: 'Bright orange-red disk during eruptions, faint glow when ash-covered. Synodic Period: ~1.275 Sebakan Years.',
    lore: 'The "Phase Maker." Its 27-day volcanic cycle divides Sebaka\'s 27-day month into three 9-day weeks.',
    rotationPeriodHours: 20,
  },
  {
      name: "Aetheris", color: "#5082C8", 
      size: 95.565, // 15.0 R⊕
      orbitRadius: 7.0 * AU_TO_UNITS, orbitPeriodDays: 4241, eccentric: true, eccentricity: 0.5, initialPhase: 0,
      type: 'Planet', classification: 'Gas Giant',
      orbitalRole: 'Fifth planet orbiting Alpha-Twilight binary', orbitalPeriod: '13.09 Sebakan years (4,241 days)', orbitalDistance: '7.0 AU (periapsis 3.5 AU, apoapsis 10.5 AU)',
      rotation: '10 hours', axialTilt: '25°', moons: 'Multiple (5–10 visible)',
      radius: '15.0 R⊕ (~1.36 RJ)', mass: '~300 M⊕ (~0.94 MJ)',
      surface: 'Banded atmosphere with blue, purple, green hues, internal heat glow.',
      characteristics: 'Very high eccentricity (e = 0.5), causing dramatic changes in size and brightness.',
      appearance: 'Varies from a large disk to a smaller point. Dominant at night. Synodic Period: ~1.083 Sebakan Years.',
      lore: 'Marks long-term cycles via size changes. Portrayed as a majestic, calming presence.',
      rotationPeriodHours: 10,
  },
  {
      name: "Gelidis",
      color: "#1E90FF",
      size: 25.484, // 4.0 R⊕
      orbitRadius: 10 * AU_TO_UNITS,
      orbitPeriodDays: 8991,
      eccentric: true,
      eccentricity: 0.1,
      initialPhase: 180,
      type: 'Planet',
      classification: 'Ice Giant',
      orbitalRole: 'First planet orbiting Beacon',
      orbitalPeriod: '~27.75 Sebakan years (8,991 days)',
      orbitalDistance: '10 AU from Beacon (periapsis 9 AU, apoapsis 11 AU)',
      rotation: '16 hours',
      axialTilt: '28°',
      moons: '2-3 (small, telescopic only)',
      radius: '4.0 R⊕',
      mass: '~15 M⊕',
      surface: 'Vast atmosphere with swirling storm systems, faint icy cloud bands.',
      characteristics: 'Remote, dimly lit by Beacon’s light. Eccentricity (e=0.1).',
      appearance: 'Faint point of light (telescopic only). Synodic Period tied to Beacon\'s orbit.',
      lore: 'Known only through advanced astronomical calculations; a mysterious, remote world.',
      rotationPeriodHours: 16,
  },
  {
      name: "Liminis",
      color: "#F5F5F5",
      size: 1.274, // 0.2 R⊕
      orbitRadius: 18.9 * AU_TO_UNITS,
      orbitPeriodDays: 26820,
      eccentric: true,
      eccentricity: 0.2,
      initialPhase: 90,
      type: 'Planet',
      classification: 'Ice Dwarf',
      orbitalRole: 'Second planet orbiting Beacon',
      orbitalPeriod: '~82.78 Sebakan years (26,820 days)',
      orbitalDistance: '18.9 AU from Beacon (periapsis 15.12 AU, apoapsis 22.68 AU)',
      rotation: '48 hours',
      axialTilt: '5°',
      moons: 'None',
      radius: '0.2 R⊕',
      mass: '~0.01 M⊕',
      surface: 'Frozen expanse of rock and ice, thin atmosphere.',
      characteristics: 'Furthest known planet. Eccentricity (e=0.2).',
      appearance: 'Tiny point of light (telescopic only). Synodic Period tied to Beacon\'s orbit.',
      lore: 'Discovered through long-duration observations, represents the edge of the known system.',
      rotationPeriodHours: 48,
  },
];
